### ISSUE TITLE
importing rules from v0.5.x does not always work

### ISSUE THREAD

**Issue by msxfm** [RequestPolicyContinued/requestpolicy#354]
<a href="https://github.com/dtfinch"><img src="https://avatars.githubusercontent.com/u/1477446?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dtfinch](https://github.com/dtfinch)**
_Wednesday Dec 05, 2012 at 23:40 GMT_
_Originally opened as https://github.com/RequestPolicy/requestpolicy/issues/354_

----

I had hundreds of rules in the last stable version, but none were imported upon upgrade to the 1.0 beta, and the UI indicates they should have been. "Show re-import options" gives an empty list, though I never told it to delete them. Using Firefox 17.

**Comment by baptx** [comment]
I tried RequestPolicyContinued (1.0.beta9.2) because original RequestPolicy (0.5.28) is not compatible with Firefox 38. Rules from old addon were not imported but are still available in pref.js. Since there is no import/export rules function in RequestPolicyContinued, what you can do is copy old rules from pref.js or use previous export of original RequestPolicy and make them compatible with requestpolicy/policies/user.json format. For example with rules like originhost.com|destinationhost.com, you get JSON formatted rules like {"o":{"h":"*.originhost.com"},"d":{"h":"*.destinationhost.com"}}. Use a text editor that has a Search+Replace function (I used Geany, shortcut Ctrl+H), then with regular expressions enabled, search \n and replace with \n{"o":{"h":"*. search again \n and replace with "}},{"o":{"h":"*. search | without regex and replace with "},"d":{"h":"

**Comment by myrdd** [comment]
Thanks for your description @baptx. The next version will support importing rules from legacy versions.

**Comment by DJ-Leith** [comment]
In #643 I have documented a *workaround* for the following situation:

The User was using RP 0.5.xx,
they did not have a recent backup of their Profile,
they did not have a 'RP Export' of their 'RP whitelist'.

When Firefox 37.0.2 became Fx 38 they could not use RP 0.5.xx.

They have a 'big whitelist' and they don't want to 'hand edit'
the data from "prefs.js" into the "user.json".

[Here is the comment.]
(https://github.com/RequestPolicyContinued/requestpolicy/issues/643#issuecomment-104451214)

**Comment by myrdd** [comment]
@baptx @DJ-Leith I've released `beta9.3`, which makes it (again) possible to import rules. To import the old rules you have to go to `about:requestpolicy?oldrules`. If old rules are present, you can find a link on the very bottom of `about:requestpolicy?yourpolicy`.

**Comment by DJ-Leith** [comment]
Thank you for both Version 0.5.29b4 and Version 1.0.beta9.3 - I am very pleased. 

I have now tested both.
I know you can't have 'both on the same Profile' at the same time.


**Summary of Tests**

**A. The 'smooth path', via RPC 0.5.29b4 - all OK.**
Fx 37, RP 0.5.28 (RP data in "prefs.js") -->
Fx 38, RPC 0.5.29b4 (RPC data in "prefs.js") -->
Fx 38, RPC 1.0.beta9.3 (RPC data in "user.json").

After RPC 1.0.beta9.3 you can use the 
<code>about:requestpolicy?oldrules</code>
to "Delete old rules" from "prefs.js".

All OK, the main 'possible issue' is 'finding RPC 0.5.29b4' on AMO,
because it has only just been uploaded (2015-05-22).
https://addons.mozilla.org/en-US/firefox/addon/requestpolicy-continued/


**B. A more typical path, via RPC 1.0.beta9.2**
Fx 37, RP 0.5.28 (RP data in "prefs.js") -->
Fx 38, RPC 1.0.beta9.2 (RPC data in "user.json")

To get the data into the "user.json" you had to:
B1. copy an existing "user.json" or
B2. 'hand edit', as **baptx** documented (above), the data from "prefs.js" into the "user.json" or
B3. use the *workaround* (above). 
In this test, I ensured that the 'effective whitelist' was the 
**same** in "prefs.js" and "user.json".

Then update to:
Fx 38, RPC 1.0.beta9.3 (RPC data in "user.json").
All OK.


In Tests **C** and **D**
I ensured that the 'effective whitelist' was 
**different** in "prefs.js" vs "user.json".
I wanted to test **both** an 'extra rule' and a 'missing rule'.


**C. Another typical path, via RPC 1.0.beta9.2, "user.json" has an 'extra rule'**

Fx 37, RP 0.5.28 (RP data in "prefs.js") -->
Fx 38, RPC 1.0.beta9.2 (RPC data in "user.json")

To get the data into the "user.json" I did:

C2. 'hand edit' the data from "prefs.js" into the "user.json".

In this test "C" the "user.json" has an 'extra rule' (vs "prefs.js").

Then update to:
Fx 38, RPC 1.0.beta9.3 (RPC data in "user.json").

The 'extra rule' was still there, expected - OK.


**D. Another typical path, via RPC 1.0.beta9.2, "user.json" has one 'missing rule'**

Fx 37, RP 0.5.28 (RP data in "prefs.js") -->
Fx 38, RPC 1.0.beta9.2 (RPC data in "user.json")

To get the data into the "user.json" I did:

D2. 'hand edit' the data from "prefs.js" into the "user.json".
In this test "D" the "user.json" has one 'missing rule' (vs "prefs.js").

Then update to:
Fx 38, RPC 1.0.beta9.3 (RPC data in "user.json").

In this case the
<code>about:requestpolicy?oldrules</code>
and then
"Show re-import options." link
and then the "Import Old Rules" button
did allow a 're-import of old rules'.
The "user.json" now had the 'same rules' as "prefs.js" - excellent!


**E. Direct from RP 0.5.28 to RPC 1.0.beta9.3**
Fx 37, RP 0.5.28 (RP data in "prefs.js") -->
Fx 38, RPC 1.0.beta9.3 (RPC data in "user.json").

All OK, easy.

In all cases (A, B, C, D or E):
After you have updated to RPC 1.0.beta9.3 you can use the 
<code>about:requestpolicy?oldrules</code>
to "Delete old rules" from "prefs.js".

For **Tests in Detail** in particular A using RPC 0.5.29b4 see [this comment]
(https://github.com/RequestPolicyContinued/requestpolicy/issues/643#issuecomment-104771944) in #643.

**Comment by l-i-r-n-f-a** [comment]
Thank you for continuing RP. Unfortunitely, even with beta9.3 importing rules still isn't working for me. I tested a few install/re-install variations in two different profiles. Upgrading from legacy 0.5 to beta9.3 -> nothing auto-imported, nothing to be found under about:requestpolicy?oldrules (shouldn't there be a list of my rules?) and the import button there hasn't any effect either. Upgrading 0.5 to 0.5.29b4 (resp. removing beta9.3 and installing 0.5.29b4) works fine though. I created hundreds of rules over the years and a correct (auto-)import/transfer to 1.0 is critical to me. Thank you.

**Comment by myrdd** [comment]
> Upgrading from legacy 0.5 to beta9.3 -> nothing auto-imported

Auto-import still has issues, I know that, which is the reason why this issue is still open.

> nothing to be found under about:requestpolicy?oldrules (shouldn't there be a list of my rules?)

The list should appear when you click on the link (with english locale it's *„Show re-import options.“*). Please re-check if this works! If it doesn't, please check the Browser Console for errors that appear when you open `about:requestpolicy?oldrules` and click on that link.

**Comment by l-i-r-n-f-a** [comment]
Hi myrdd, thanks for the quick reply. I really appreciate it. Ok, it doesn't work, so I checked the Browser Console. After opening about:requestpolicy?oldrules and clicking „Show re-import options.“ the error messages in my daily profile are:

NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIURI.host] common.js:105:0

and

ReferenceError: reference to undefined property a[h] jquery.min.js:2:23266

When clicking the "import old rules" button anyway, this comes up:
uncaught exception: rules is undefined or empty

I tested this in an all fresh profile as well and the error messages were the same except for the ReferenceError which doesn't come up there.

**Comment by myrdd** [comment]
> `NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIURI.host] common.js:105:0`

Thank you @l-i-r-n-f-a! This helps a lot! I now know the problem here are rules that are specifying an URI without a host! The error you got was thrown on [this line](https://github.com/RequestPolicyContinued/requestpolicy/blob/v1.0.beta9.3/src/content/settings/common.js#L105).

-------------

#### Note to myself / FYI:

The import functionality should support the following special cases:

1. URIs without an "authority" part – see [STD 66](https://tools.ietf.org/html/std66#appendix-A)
2. invalid URIs

How should RPC handle those cases?

1. There shouldn't be any error. (Such a rule looks like `mediasource:` in the v0.5 rule lists.)
2. The user should be notified. Two sub-cases:
  1. ***Automatic import*** will omit the erroneous rules. The menu will show a notification to the user.
  2. On the ***import page*** (`about:requestpolicy?oldrules`)
    - the button for removing the old rules will show a warning when there are invalid rules that don't have been imported.
    - there will be two tables: one for valid, one for invalid rules. When the user clicks on the *import* button, the invalid rules won't be imported.

**Comment by myrdd** [comment]
@l-i-r-n-f-a I've created a quick patch for the import page. Can you please check if it works? You have to create the XPI yourself. The patch is on the branch [`issue-354-test`](https://github.com/RequestPolicyContinued/requestpolicy/tree/issue-354-test). Tell me if you need help.

**Comment by l-i-r-n-f-a** [comment]
@myrdd Wow, it seems to work now, thank you :) I tested this in a cloned copy of my working (daily) profile and in a fresh one. The first try to import the old rules list resulted in a seemingly endlessly reoccurring unresponding script warning for chrome://requestpolicy/content/settings/jquery.min.js:2 in the fresh profile, where it only worked after the second try. The test in the cloned working profile (with lots of other addons in it) was an instant success though. I don't know if this is of any relevance for possible trouble shooting.

**Comment by Fak3** [comment]
I just upgraded from 0.5.30pre1 to 1.0.beta10.2 and all my rules from old version was not imported. When i removed new version and enabled older version back, all rules are still present in old version.
