### ISSUE TITLE
Opening link in new tab treated as redirect.

### ISSUE THREAD

**Issue by Fak3** [RequestPolicyContinued/requestpolicy#723]
For a coulpe of days i am experiencing this bug:
Given a page with external link on it, when i middle-click the link, or right-click + "open in new tab", requestpolicy redirect warning appears on current tab, new blank tab opened without content. When i click "allow" on the warning, that opened blank new tab stay blank, but instead the page in current tab gets replaced by new page.

For example on page:
http://sound.stackexchange.com/questions/17327/glitchy-sound-effects
Middle-click on the link in any answer.

Rquestpolicy: 0.5.30pre1
Firefox: 41.0.2

**Comment by nodiscc** [comment]
Hi, this bug is fixed in RequestPolicy Continued 1.x beta, check https://requestpolicycontinued.github.io/. RP 0.5 is not maintained anymore (except compatibility for newer Firefox versions).

Does this solve your problem?

**Comment by Fak3** [comment]
I tried the new version, it does not have this bug. But all my rules are gone. Is there any way to import rules from old version?

**Comment by myrdd** [comment]
Hi @Fak3, you're probably suffering from issue #354. It's one of the issues not yet fixed in the 1.0 version, see [this list of issues](https://github.com/RequestPolicyContinued/requestpolicy/issues?q=is%3Aopen+is%3Aissue+label%3A%221.0+vs+0.5%22).

**Comment by myrdd** [comment]
@Fak3 you can now switch to 1.0 – you can manually import your rules on `about:requestpolicy?oldrules`.

I'm closing this issue because 0.5 is not supported anymore.
